---
# tasks file for apt
- name: update apt-cache
  apt: update_cache=yes cache_valid_time=3600

- name: install apt repos
  apt_repository: repo="{{ item.name }}" state="present"
  with_items: "{{ apt_repos }}"

- name: install apt packages
  apt: name="{{ item.name }}" state="latest"
  with_items: "{{ apt_pkgs }}"

- name: upgrade apt safely
  apt: upgrade=safe

- name: Copy the "10periodic.j2" to the "/etc/apt/apt.conf.d/"
  template:
   src: 10periodic.j2
   dest: /etc/apt/apt.conf.d/10periodic
   owner: root
   group: root
   mode: 0644

- name: Copy the "50unattended-upgrades.j2" to the "/etc/apt/apt.conf.d/"
  template:
   src: 50unattended-upgrades.j2
   dest: /etc/apt/apt.conf.d/50unattended-upgrades
   owner: root
   group: root
   mode: 0644
