---
# tasks file for php-mysql
- name: Define php_mysql_package.
  set_fact:
    php_mysql_package: "{{ __php_mysql_package }}"
  when: php_mysql_package is not defined

# Installation.
- name: Install PHP MySQL dependencies.
  apt:
    name: "{{ php_mysql_package }}"
    state: present
  notify:
    - restart webserver
    - restart php-fpm
